In [19]:
import numpy as np

#Ejercicio Nro1:Cree un objeto ndarray unidimensional con una longitud de 10 y todos 0, y luego haga que el quinto elemento sea igual a 1

ndarray = np.zeros((1, 10))
ndarray[0][4] = 1

print(ndarray)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]]


In [76]:
#Ejercicio Nro2: Crea un objeto ndarray con elementos del 10 al 49.
ndarray = np.arange(10,50)
print(ndarray)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


In [81]:
#Ejercicio Nro3:  Cree una matriz bidimensional de 4 * 4 y genere el tipo de elemento de matriz.
matriz = np.array([[1,2,3,4],[5,6,7,8,],[9, 10, 11, 12],[13,14,15,16]])
print(matriz)
print(f"El tipo de matriz es: {matriz.dtype}")

print('-' * 50)

ndarray = np.ones((4,4))
print(ndarray) 
print(f"El tipo de matriz es: {matriz.dtype}")


[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]
El tipo de matriz es: int32
--------------------------------------------------
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
El tipo de matriz es: int32


In [95]:
#Ejercicio Nro4: Convierta el tipo de datos en la 3 pregunta a float64.
ndarray = np.ones((4,4))
ndarray.dtype = "float64"
print(ndarray.dtype)

float64


In [126]:
#Ejercicio Nro5: Cree una matriz bidimensional, use el índice para obtener los datos en la segunda fila, primera columna y tercera fila, segunda columna.
ndarray = np.arange(0,12).reshape(3,4)
print(ndarray)

print('-' * 50)

print(f"El dato de la segunda fila, pimera columna es: {ndarray[1][0]}")
print(f"El dato de la tercera fila, pimera columna es: {ndarray[2][0]}")
print(f"El dato de la tercera fila, segunda columna es: {ndarray[2][1]}")

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
--------------------------------------------------
El dato de la segunda fila, pimera columna es: 4
El dato de la tercera fila, pimera columna es: 8
El dato de la tercera fila, segunda columna es: 9


In [137]:
#Ejercicio Nro6: Utilice un método para obtener los datos en la primera, segunda y tercera columnas de la matriz en las 5 pregunta.
ndarray1 = ndarray
print(ndarray1)

print('-' * 15)

print(ndarray1[:3,0])
print(ndarray1[:3,1])
print(ndarray1[:3,2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------
[0 4 8]
[1 5 9]
[ 2  6 10]


In [144]:
#Ejercicio Nro7:  usando el mismo método del ejercicio anterior obtenga los datos de la segunda fila, segunda columna y tercera columna de la matriz 
#del ejercicio 5.
ndarray2 = ndarray
print(ndarray1)

print('-' * 15)

print(ndarray2[1][1])
print(ndarray2[1][2])

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
---------------
5
6


In [150]:
#Ejercicio Nro8: generar una matriz con numeros aleatorios y sumar todos sus valores, luego sus filas y columnas a parte.
matriz = np.random.randint(0,11,size=(5,4))
print(matriz)
print('-' * 25)

total = matriz.sum()
col = matriz.sum(axis=0)
filas = matriz.sum(axis=1)
print(f"La suma total es de: {total} ")
print(f"La suma de las filas es de: {filas} ")
print(f"La suma de las columnas es de: {col} ")



[[6 1 0 7]
 [4 0 7 9]
 [5 6 7 2]
 [3 8 7 6]
 [4 3 6 4]]
-------------------------
La suma total es de: 95 
La suma de las filas es de: [14 20 20 24 17] 
La suma de las columnas es de: [22 18 27 28] 
